linters-settings:
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - (go.uber.org/zap/SugaredLogger).DPanicf
          - (go.uber.org/zap/SugaredLogger).Debugf
          - (go.uber.org/zap/SugaredLogger).Errorf
          - (go.uber.org/zap/SugaredLogger).Fatalf
          - (go.uber.org/zap/SugaredLogger).Infof
          - (go.uber.org/zap/SugaredLogger).Panicf
          - (go.uber.org/zap/SugaredLogger).Warnf
  misspell:
    locale: US
  errcheck:
    check-blank: false
  forbidigo:
    forbid:
      - ^fmt\.Print.*(# likely just for debugging)?$
      - if [!]?rows.Next*(# use dblib.EnsureSingle(Struct)Scan)$
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  enable-all: false
  disable-all: true
  fast: true
  enable:
    - bodyclose
    - errcheck
    - copyloopvar
    - forbidigo
    - gocritic
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilnil
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unused
    - unconvert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
