schema = 3

[mod]
  [mod."github.com/Kunde21/markdownfmt/v3"]
    version = "v3.1.0"
    hash = "sha256-wku1uear1V9gPsZ/fUsGe+k2OK/KlwwpFRA9oWJb92k="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.0"
    hash = "sha256-JaGYNQwDxFCsLwzYVoJY4RUpP4dtiRlV14t2dVAg4oQ="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v1.1.0-alpha.2-proton"
    hash = "sha256-ITgoUrlQHhesVk6YvHqRrUukjijE74IZnJkf6tMSTzY="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.3"
    hash = "sha256-d1lUB0kToOsPYfRmEh9SO+iVipgmsRs4xQkj1xlY9og="
  [mod."github.com/apparentlymart/go-textseg/v15"]
    version = "v15.0.0"
    hash = "sha256-960kVVQSGhx1Gww5cfoNeM3yXaA4dwlv+AFhKh6EGlA="
  [mod."github.com/armon/go-radix"]
    version = "v1.0.0"
    hash = "sha256-A5SNdGtw8I6ngk9U3p+rKu6KB7inSngqmdnJl74EM9Q="
  [mod."github.com/bgentry/speakeasy"]
    version = "v0.1.0"
    hash = "sha256-Gt1vj6CFovLnO6wX5u2O4UfecY9V2J9WGw1ez4HMrgk="
  [mod."github.com/cloudflare/circl"]
    version = "v1.3.8"
    hash = "sha256-6FbUbOjD8UDb2DIUzVCtI6S+Ja7Dk1pQLc0j0SWZaCk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/cli"]
    version = "v1.1.6"
    hash = "sha256-/rcjznXypJYwDLDAQ4G7hFkeugXRNx0XSftGK76Js5E="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-checkpoint"]
    version = "v0.5.0"
    hash = "sha256-QZe6mSoWT4M3B8BGlslHr/1eLrYfzvHhhmHQ69m0QLw="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-cty"]
    version = "v1.4.1-0.20200414143053-d3edf31b6320"
    hash = "sha256-corGsnYW1m9ktTDMBjfggM2GRZKSeG8dPDAMJ5nzjss="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v1.6.3"
    hash = "sha256-BK2s+SH1tQyUaXCH4kC0/jgqiSu638UFbwamfKjFOYg="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-plugin"]
    version = "v1.6.0"
    hash = "sha256-NeY86Z+qJwt0NPV4cNmWDiTryDPSiyKMkS1ivRX9ThE="
  [mod."github.com/hashicorp/go-uuid"]
    version = "v1.0.3"
    hash = "sha256-8893qBbaug2yhxElowSrl3PrfhYlQ7cZ71QBgZWqpHE="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.6.0"
    hash = "sha256-UV0equpmW6BiJnp4W3TZlSJ+PTHuTA+CdOs2JTeHhjs="
  [mod."github.com/hashicorp/hc-install"]
    version = "v0.6.4"
    hash = "sha256-ksptXXU6vEi9eZrrA0TDvmC6L+gL2XZt511Tsqmix+w="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.20.1"
    hash = "sha256-Uqg+r9sEEWf1af7iig07cRcySEwkswjg9TXN7VrgIh4="
  [mod."github.com/hashicorp/logutils"]
    version = "v1.0.0"
    hash = "sha256-e8t8Dm8sp/PzKClN1TOmFcrTAWNh4mZHSW7cAjVx3Bw="
  [mod."github.com/hashicorp/terraform-exec"]
    version = "v0.20.0"
    hash = "sha256-pZAV6JZiN9NCPFuQI3IgVSmqstAVDlgLYT5rOwo3XqM="
  [mod."github.com/hashicorp/terraform-json"]
    version = "v0.21.0"
    hash = "sha256-u1uqTdFAPk2dQeR1YtBiRLKVcJbzvKW79MVQBpBQK5k="
  [mod."github.com/hashicorp/terraform-plugin-docs"]
    version = "v0.17.0"
    hash = "sha256-+iN1rjLr/nGNSvldkxG80ay9jBpbechPgZ3Hk+MxajY="
  [mod."github.com/hashicorp/terraform-plugin-framework"]
    version = "v1.8.0"
    hash = "sha256-PQ4k2eZw9rdMVSLZTM0ajD9cNI5U5bjYOZ4wsRjmW5g="
  [mod."github.com/hashicorp/terraform-plugin-framework-timeouts"]
    version = "v0.4.1"
    hash = "sha256-PucBfXDGKplDSTEEUwtnNIo3rmsVw0HfXK5lXM/tPZY="
  [mod."github.com/hashicorp/terraform-plugin-framework-validators"]
    version = "v0.12.0"
    hash = "sha256-qKTlQzu6gzuU8Y4L2x8y0A5Yhxv19dixpmjMbA6a8Fc="
  [mod."github.com/hashicorp/terraform-plugin-go"]
    version = "v0.22.2"
    hash = "sha256-t4Fm6+yh/A6hsDprLxg4PzTI6VlEVwo46rMNNzS2aEQ="
  [mod."github.com/hashicorp/terraform-plugin-log"]
    version = "v0.9.0"
    hash = "sha256-YnzFZQIzb+NHKb7qVBXk+7FGelkSVWGp7ij1G1RUIUg="
  [mod."github.com/hashicorp/terraform-plugin-sdk/v2"]
    version = "v2.33.0"
    hash = "sha256-Vv4G1YgP1kA0o+eaDip219Y4ISqerfwcXD/XzcvdGkg="
  [mod."github.com/hashicorp/terraform-plugin-testing"]
    version = "v1.7.0"
    hash = "sha256-tOaiz5IdsFJY87ExfsSRUTdmzCQVobY2xWwP5gapxBE="
  [mod."github.com/hashicorp/terraform-registry-address"]
    version = "v0.2.3"
    hash = "sha256-evVRKhphTvhCvdT1XwcMXbbbKBnaZhdxEU93sot4yp0="
  [mod."github.com/hashicorp/terraform-svchost"]
    version = "v0.1.1"
    hash = "sha256-kY0Dcmr4CXHaSx1keJrEfsgsxYhxh8Abh5kicmlZDGQ="
  [mod."github.com/hashicorp/yamux"]
    version = "v0.1.1"
    hash = "sha256-jr4ZFM3XHSwGoZcRcmmdGTq4IqxBTnimojIPDgK0USU="
  [mod."github.com/huandu/xstrings"]
    version = "v1.3.3"
    hash = "sha256-xtauGYk7SnC2LMnCD+dc5dBhNFNfFnkWXcKyHQNaaK0="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.15"
    hash = "sha256-HyN1PxCZW2IRns9VDkwxMHtDvdDwaRgat0wcHf53B0w="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.9"
    hash = "sha256-dK/kIPe1tcxEubwI4CWfov/HWRBgD/fqlPC3d5i30CY="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-testing-interface"]
    version = "v1.14.1"
    hash = "sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/oklog/run"]
    version = "v1.1.0"
    hash = "sha256-U4IS0keJa4BSBSeEBqtIV1Zg6N4b0zFiKfzN9ua4pWQ="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/posener/complete"]
    version = "v1.2.3"
    hash = "sha256-/17KFHD0SsGALg9iLXNIdvVFcotOO+H6bOOD5SY0MVs="
  [mod."github.com/russross/blackfriday"]
    version = "v1.6.0"
    hash = "sha256-tyqVArfv2d9sKGaG83SyZm//5QxLtGp1+qLgaz0SwAw="
  [mod."github.com/shopspring/decimal"]
    version = "v1.3.1"
    hash = "sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA="
  [mod."github.com/spf13/cast"]
    version = "v1.5.0"
    hash = "sha256-Pdp+wC5FWqyJKzyYHb7JCcV9BoJk/sxQw6nLyuLJvuQ="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.11"
    hash = "sha256-lh25/VSjgpoM7P4zUg6MOSiA4j438STUyLKd18XkpEI="
  [mod."github.com/vmihailenco/msgpack"]
    version = "v4.0.4+incompatible"
    hash = "sha256-gA3l8Ma1XVja+C8XJzgRTQVb1htbsh4yrbnOu6cuw9U="
  [mod."github.com/vmihailenco/msgpack/v5"]
    version = "v5.4.1"
    hash = "sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk="
  [mod."github.com/vmihailenco/tagparser/v2"]
    version = "v2.0.0"
    hash = "sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0="
  [mod."github.com/yuin/goldmark"]
    version = "v1.6.0"
    hash = "sha256-0PeGjGxxM7lUSx2dn8yPUBpilPQzEN9nkgf3s+5zGTY="
  [mod."github.com/yuin/goldmark-meta"]
    version = "v1.1.0"
    hash = "sha256-Q/kRP4rpS3r24HYBvPTiuKNbf+PUMVsEp2m6yOblth0="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.14.4"
    hash = "sha256-Pc54uTUUxMTROex41VWFYu6pAqUxCDACAuDdMMwiW1g="
  [mod."golang.org/x/crypto"]
    version = "v0.22.0"
    hash = "sha256-2+u9nd32+Bi7EEv7QFc12CRTbfV7DApNv+yKIr7+lTw="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240222234643-814bf88cf225"
    hash = "sha256-DM6/KUjyqyuqXai7UH1vMsoKXQAlYfcHTwK1dHqjRAc="
  [mod."golang.org/x/mod"]
    version = "v0.17.0"
    hash = "sha256-CLaPeF6uTFuRDv4oHwOQE6MCMvrzkUjWN3NuyywZjKU="
  [mod."golang.org/x/net"]
    version = "v0.24.0"
    hash = "sha256-w1c21ljta5wNIyel9CSIn/crPzwOCRofNKhqmfs4aEQ="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.19.0"
    hash = "sha256-cmuL31TYLJmDm/fDnI2Sn0wB88cpdOHV1+urorsJWx4="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/tools"]
    version = "v0.20.0"
    hash = "sha256-g5T5FrNPO/cf2W1lc+/93FcFB3HftPjqI72FueD9Wt8="
  [mod."google.golang.org/appengine"]
    version = "v1.6.8"
    hash = "sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240415180920-8c6c420018be"
    hash = "sha256-P5SBku16dYnK4koUQxTeGwPxAAWH8rxbDm2pOzFLo/Q="
  [mod."google.golang.org/grpc"]
    version = "v1.63.2"
    hash = "sha256-RmtVjYLam97k7IHTHU7Gn16xNX+GvA9AiLKlQwOiZXU="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
