query GetPostgresParameters($projectId: ID!, $serviceId: ID!) {
    getPostgresParameters (data:{
        projectId: $projectId,
        serviceId: $serviceId
    }) {
        string_parameters {
            info {
                name
                is_user_editable
                requires_restart
                is_pending_restart
                is_user_modified
            }
            current_value
            allowed_values
        }
        numeric_parameters {
            info {
                name
                is_user_editable
                requires_restart
                is_pending_restart
                is_user_modified
            }
            unit
            current_value
        }
    }
}
